[package]
name = "kaile/newcycle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
hitboxclass = "naithss/hitboxclass@1.1.3"
bytenet = "ffrostflame/bytenet@0.4.6"